version: "3.7"

# Composefile for developing with alice. A postgres server
# and the ui live dev server are started.

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: alice 
      POSTGRES_PASSWORD: alice 
      POSTGRES_DB: alice 
    ports:
      - 5432:5432
    networks:
      - aliceDev

  ui:
    build:
      dockerfile: Containerfile
      context: containers/ui/
    volumes:
      - ../ui:/ui
    environment:
      DANGEROUSLY_DISABLE_HOST_CHECK: "true"
    ports:
      - 3000:3000
    command:
      - start 
    networks:
      - aliceDev

  backend:
    build: 
      dockerfile: dev/containers/backend/Containerfile
      context: ../.
    volumes:
      - ../.:/src/alice-lg
      - ../etc/alice-lg:/etc/alice-lg
      # - ../ui/public:/build
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - aliceDev


  bgp:
    image: jauderho/gobgp:latest

    ports:
      - "179:179"
      - "50051:50051"

    volumes:
      - ./gobgpd.yml:/etc/gobgpd/gobgpd.yml
    command: ["gobgpd", "-t", "yaml", "-f", "/etc/gobgpd/gobgpd.yml"]
    networks:
      - aliceDev


networks:
  aliceDev:
    name: "aliceDev"
    ipam: 
      driver: default
      config:
        - subnet: 192.168.58.0/24